/** Shared strings for Tools and browser notifications. Portuguese is the source. */
(function(root) {
  const rows = [
    ['Farm de Ouro','Gold Farm','Farm de Oro','Farm d’or'],
    ['Metas','Goals','Metas','Objectifs'],
    ['Meta de XP','XP goal','Meta de XP','Objectif XP'],
    ['Meta de Ouro','Gold goal','Meta de oro','Objectif d’or'],
    ['Parar XP na meta','Stop XP at goal','Parar XP en la meta','Arrêter XP à l’objectif'],
    ['Parar Ouro na meta','Stop Gold at goal','Parar oro en la meta','Arrêter l’or à l’objectif'],
    ['Metas contam ganhos da sessão. Zero desativa o limite.','Goals count session earnings. Zero disables a limit.','Las metas cuentan ganancias de la sesión. Cero desactiva el límite.','Les objectifs comptent les gains de la session. Zéro désactive la limite.'],
    ['Salvar metas','Save goals','Guardar metas','Enregistrer les objectifs'],
    ['Resultados','Results','Resultados','Résultats'],
    ['Sessão e rendimento','Session and performance','Sesión y rendimiento','Session et rendement'],
    ['Gráficos','Charts','Gráficos','Graphiques'],
    ['Ganhos por sessão','Earnings per session','Ganancias por sesión','Gains par session'],
    ['Partidas e giros por sessão','Games and spins per session','Partidas y giros por sesión','Parties et tours par session'],
    ['Sem dados suficientes para o gráfico','Not enough data for the chart yet','Datos insuficientes para el gráfico','Pas assez de données pour le graphique'],
    ['Dados e histórico','Data and history','Datos e historial','Données et historique'],
    ['Zerar sessão de XP','Reset XP session','Reiniciar sesión de XP','Réinitialiser la session XP'],
    ['Zerar sessão de Ouro','Reset Gold session','Reiniciar sesión de oro','Réinitialiser la session or'],
    ['Zerar tudo','Reset both sessions','Reiniciar ambas sesiones','Réinitialiser les deux sessions'],
    ['Zerar encerra a farm e salva a sessão no histórico. Não altera o saldo da conta.','Reset stops the farm and saves the session in history. Your account balance is unchanged.','Reiniciar detiene el farm y guarda la sesión en el historial. No modifica el saldo de la cuenta.','Réinitialiser arrête le farm et conserve la session dans l’historique. Le solde du compte reste inchangé.'],
    ['Exportar CSV','Export CSV','Exportar CSV','Exporter CSV'],
    ['Últimas sessões','Recent sessions','Últimas sesiones','Dernières sessions'],
    ['Exibição','Display','Visualización','Affichage'],
    ['Mostrar níveis ocultos','Show hidden levels','Mostrar niveles ocultos','Afficher les niveaux masqués'],
    ['Exibe o nível de outros jogadores mesmo quando estiver oculto.','Shows other players\' level even when it is hidden.','Muestra el nivel de otros jugadores incluso cuando está oculto.','Affiche le niveau des autres joueurs même lorsqu’il est masqué.'],
    ['Perfis','Profiles','Perfiles','Profils'],
    ['Nome do perfil','Profile name','Nombre del perfil','Nom du profil'],
    ['Salvar perfil atual','Save current profile','Guardar perfil actual','Enregistrer le profil actuel'],
    ['O perfil guarda as metas e alertas já salvos.','Profiles store the goals and alerts you have saved.','Los perfiles guardan las metas y avisos ya guardados.','Les profils conservent les objectifs et alertes déjà enregistrés.'],
    ['Perfis salvos','Saved profiles','Perfiles guardados','Profils enregistrés'],
    ['Aplicar perfil','Apply profile','Aplicar perfil','Appliquer le profil'],
    ['Excluir perfil','Delete profile','Eliminar perfil','Supprimer le profil'],
    ['Sistema','System','Sistema','Système'],
    ['Notificações do navegador','Browser notifications','Notificaciones del navegador','Notifications du navigateur'],
    ['Metas atingidas','Goals reached','Metas alcanzadas','Objectifs atteints'],
    ['Notificar quando uma meta de XP ou Ouro for atingida.','Notify when an XP or Gold goal is reached.','Notificar cuando se alcance una meta de XP u oro.','Notifier quand un objectif XP ou or est atteint.'],
    ['Erros na farm','Farm errors','Errores del farm','Erreurs du farm'],
    ['Notificar quando ocorrer um erro durante a farm.','Notify when an error occurs during the farm.','Notificar cuando ocurra un error durante el farm.','Notifier en cas d’erreur pendant le farm.'],
    ['Desconexão do jogo','Game disconnection','Desconexión del juego','Déconnexion du jeu'],
    ['Notificar quando a conexão com o jogo cair.','Notify when the connection to the game drops.','Notificar cuando se pierda la conexión con el juego.','Notifier quand la connexion au jeu est perdue.'],
    ['Salvar preferências','Save preferences','Guardar preferencias','Enregistrer les préférences'],
    ['Diagnóstico','Diagnostics','Diagnóstico','Diagnostic'],
    ['Atualizar diagnóstico','Refresh diagnostics','Actualizar diagnóstico','Actualiser le diagnostic'],
    ['Restaurar padrões','Restore defaults','Restaurar valores predeterminados','Restaurer les valeurs par défaut'],
    ['Restaurar limpa metas e alertas personalizados; preserva idioma, licença, perfis e histórico.','Restore resets goals and alerts; language, license, profiles and history are preserved.','Restaurar reinicia metas y alertas; conserva idioma, licencia, perfiles e historial.','Restaurer réinitialise objectifs et alertes ; la langue, la licence, les profils et l’historique sont conservés.'],
    ['Abra o jogo para usar as ferramentas.','Open the game to use these tools.','Abre el juego para usar las herramientas.','Ouvrez le jeu pour utiliser les outils.'],
    ['Alterações não salvas','Unsaved changes','Cambios sin guardar','Modifications non enregistrées'],
    ['Salvo','Saved','Guardado','Enregistré'],
    ['Aguardando confirmação','Waiting for confirmation','Esperando confirmación','En attente de confirmation'],
    ['A alteração não foi confirmada. Recarregue o jogo.','Change not confirmed. Reload the game.','El cambio no fue confirmado. Recarga el juego.','Modification non confirmée. Rechargez le jeu.'],
    ['Confira os valores informados.','Check the entered values.','Revisa los valores introducidos.','Vérifiez les valeurs saisies.'],
    ['Informe um nome de perfil com até 40 caracteres.','Enter a profile name of up to 40 characters.','Introduce un nombre de perfil de hasta 40 caracteres.','Saisissez un nom de profil de 40 caractères maximum.'],
    ['Limite de 20 perfis. Exclua um perfil antes de criar outro.','Limit of 20 profiles. Delete one before creating another.','Límite de 20 perfiles. Elimina uno antes de crear otro.','Limite de 20 profils. Supprimez-en un avant d’en créer un autre.'],
    ['Aguarde o giro em andamento antes de zerar.','Wait for the current spin before resetting.','Espera a que termine el giro antes de reiniciar.','Attendez la fin du tour avant de réinitialiser.'],
    ['Não foi possível salvar no navegador.','Could not save in the browser.','No se pudo guardar en el navegador.','Impossible d’enregistrer dans le navigateur.'],
    ['Sem perfis salvos','No saved profiles','Sin perfiles guardados','Aucun profil enregistré'],
    ['Sem sessões registradas','No recorded sessions','Sin sesiones registradas','Aucune session enregistrée'],
    ['Sem meta','No goal','Sin meta','Aucun objectif'],
    ['Meta concluída','Goal reached','Meta alcanzada','Objectif atteint'],
    ['Meta atingida','Goal reached','Meta alcanzada','Objectif atteint'],
    ['Ganhos','Earnings','Ganancias','Gains'],
    ['Partidas','Matches','Partidas','Parties'],
    ['Tempo ativo','Active time','Tiempo activo','Temps actif'],
    ['XP por hora','XP per hour','XP por hora','XP par heure'],
    ['Ouro por hora','Gold per hour','Oro por hora','Or par heure'],
    ['Faltam','Remaining','Restante','Restant'],
    ['Tempo estimado','Estimated time','Tiempo estimado','Durée estimée'],
    ['A estimativa usa a média da sessão e pode variar.','Estimates use the session average and may vary.','La estimación usa la media de la sesión y puede variar.','L’estimation utilise la moyenne de la session et peut varier.'],
    ['Em atividade','Running','En actividad','En cours'],
    ['Parada','Stopped','Detenido','Arrêté'],
    ['Confirmar reinício dos contadores? A farm será parada e a sessão atual ficará no histórico.','Reset counters? The farm will stop and the current session will remain in history.','¿Reiniciar contadores? El farm se detendrá y la sesión quedará en el historial.','Réinitialiser les compteurs ? Le farm sera arrêté et la session conservée dans l’historique.'],
    ['Restaurar as metas e alertas padrão?','Restore default goals and alerts?','¿Restaurar metas y alertas predeterminados?','Restaurer les objectifs et alertes par défaut ?'],
    ['Excluir o perfil selecionado?','Delete the selected profile?','¿Eliminar el perfil seleccionado?','Supprimer le profil sélectionné ?'],
    ['Aplicar este perfil e substituir as metas atuais?','Apply this profile and replace current goals?','¿Aplicar este perfil y sustituir las metas actuales?','Appliquer ce profil et remplacer les objectifs actuels ?'],
    ['Primeiro salve as alterações das metas e alertas.','Save changes to goals and alerts first.','Guarda primero los cambios de metas y alertas.','Enregistrez d’abord les modifications des objectifs et alertes.'],
    ['Extensão','Extension','Extensión','Extension'],
    ['Motor do jogo','Game engine','Motor del juego','Moteur du jeu'],
    ['Dados da conta','Account data','Datos de la cuenta','Données du compte'],
    ['Dados do inventário','Inventory data','Datos del inventario','Données d’inventaire'],
    ['Autenticação','Authentication','Autenticación','Authentification'],
    ['Roleta','Wheel','Ruleta','Roue'],
    ['Permissão de notificações','Notification permission','Permiso de notificaciones','Autorisation des notifications'],
    ['Disponível','Available','Disponible','Disponible'],
    ['Aguardando dados','Waiting for data','Esperando datos','En attente de données'],
    ['Bloqueada','Blocked','Bloqueado','Bloquée'],
    ['Atualização','Updated','Actualización','Actualisation'],
    ['Farm de XP','XP Farm','Farm de XP','Farm XP'],
    ['A farm encontrou um erro. Abra a extensão para conferir.','The farm encountered an error. Open the extension for details.','El farm encontró un error. Abre la extensión para revisarlo.','Le farm a rencontré une erreur. Ouvrez l’extension pour en savoir plus.'],
    ['A conexão com o jogo foi encerrada.','The game connection was closed.','Se cerró la conexión con el juego.','La connexion au jeu a été fermée.'],
    ['Verificação solicitada','Refresh requested','Actualización solicitada','Actualisation demandée'],
  ];
  const dict = new Map(rows.map(row=>[row[0],row]));
  root.toolsText = (source, language = 'pt-BR') => dict.get(source)?.[Math.max(0,['pt-BR','en','es','fr'].indexOf(language))] ?? source;
})(globalThis);
